In [281]:
import numpy as np
#Create and print a one-dimensional NumPy array, a, from the following Python list; [1,2,3,4,5,6,7,8,9]
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [282]:
#Print the shape of array a, to confirm that it’s (9,)
a=np.shape([1,2,3,4,5,6,7,8,9])
print(a)

(9,)


In [283]:
#Print the data type of array a
a=np.array([1,2,3,4,5,6,7,8,9])
print(a.dtype)

int32


In [284]:
#Create and print a one-dimensional NumPy array, b, of data type float, from the following Python list; [1,2,3,4,5,6,7,8,9,10,11,12]
b=np.array([1,2,3,4,5,6,7,8,9,10,11,12] , dtype=float)
print(b)




[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [285]:
#Print the data type of NumPy array b
b=np.array([1,2,3,4,5,6,7,8,9,10,11,12] , dtype=float)
print(b.dtype)

float64


In [286]:
#Create and print a row vector, called row_vector, of shape (1, 4), containing the sequence of numbers 1, 2, 3, 4
column_vector = np.array([1, 2 , 3 , 4])
print(row_vector.reshape(1,4))


[[1 2 3 4]]


In [287]:
#Create and print a column vector, called column_vector, of shape (4, 1), containing the sequence of numbers 1, 2, 3, 4
column_vector = np.array([1, 2, 3, 4])
print(column_vector.reshape(4,1))

[[1]
 [2]
 [3]
 [4]]


In [288]:

a = np.array([[1], [2], [3], [4]])
c = a.reshape(1,4)    # row vector
print(c)

[[1 2 3 4]]


In [289]:
##Create and print array c in the shape of a (3,3) two-dimensional array containing the following sequence of numbers 1, 2, 3, 4, 5, 6, 7, 8, 9
c = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(c.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [290]:
#1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12

d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] , dtype=float)
print(d.reshape(2,2,3))
print("The shape of array d is " + str(d.shape) + ".")


[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
The shape of array d is (12,).


In [291]:
#Print the shapes of arrays a, b, c and d
a=np.shape([1,2,3,4,5,6,7,8,9])

b=np.shape([1,2,3,4,5,6,7,8,9,10,11,12])

c = np.shape([[1,2,3] , [4,5,6] , [7,8,9]])

d = np.shape([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])



print('The shape of array a is',a)
print('The shape of array b is',b)
print(c)
print(d)




The shape of array a is (9,)
The shape of array b is (12,)
(3, 3)
(12,)


In [292]:
a=np.ndim([1,2,3,4,5,6,7,8,9])
b=np.ndim([1,2,3,4,5,6,7,8,9,10,11,12])
c = np.ndim([[1,2,3] , [4,5,6] , [7,8,9]])
d = np.ndim([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(a)
print(b)
print(c)
print(d)



1
1
2
1


In [293]:
#######
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.array([1,2,3,4,5,6,7,8,9,10,11,12] , dtype=float)
c = np.array([[1,2,3] , [4,5,6] , [7,8,9]] )
d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],  dtype=float)

print("Array a contains " + str(a.size) + " elements, of type " + str(a.dtype) + ".")
print("Array b contains " + str(b.size) + " elements, of type " + str(b.dtype) + ".")
print("Array c contains " + str(c.size) + " elements, of type " + str(c.dtype) + ".")
print("Array d contains " + str(d.size) + " elements, of type " + str(d.dtype) + ".")

Array a contains 9 elements, of type int32.
Array b contains 12 elements, of type float64.
Array c contains 9 elements, of type int32.
Array d contains 12 elements, of type float64.


In [294]:
#Part3

x = a.reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [295]:
#Create and print array y by reshaping array b to shape (2,2,3)
y = b.reshape(2,2,3)
print(y)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


In [296]:
#Part4
#Print the min, max, sum and mean of arrays a and x
x = a.reshape(3,3)
print('Tha max  of array x is :' , x.max() ,' and th min is  : ' , x.min() ) 

y = b.reshape(2,2,3)
print('Tha max  of array x is :' , y.max() ,' and th min is  : ' , y.min() ) 



Tha max  of array x is : 9  and th min is  :  1
Tha max  of array x is : 12.0  and th min is  :  1.0


In [297]:
#Add arrays c and x to produce array p, then print p
v = c + x
print(v)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [298]:
d = b.reshape(2,2,3)
y = b.reshape(2,2,3)
print(d* y-2)
#q = (d * y) - 2

[[[ -1.   2.   7.]
  [ 14.  23.  34.]]

 [[ 47.  62.  79.]
  [ 98. 119. 142.]]]


In [299]:
#Create and print array a of shape (3,5) containing only zeros
z = np.zeros((3,5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [300]:
#Create and print array b of shape (2,2,2) containing only uninitialized values. Note that uninitialized values will appear random, and your results will likely be different from those shown in the example.
#.....
b = np.empty((2,2,2)) 
print(b)

[[[0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 7.68766145e-321]
  [6.79038653e-313 8.01097888e-307]]]


In [301]:
#Create and print array c containing the even integers between 1 and 16 using the .arange method

#c = np.arange(1,17,3)
#output: [ 2  4  6  8 10 12 14 16]
c = np.arange(2,17,2)
print(c)


[ 2  4  6  8 10 12 14 16]


In [302]:
#Create and print array d containing the odd integers between 1 and 16 using the .linspace method
#output : [ 1  3  5  7  9 11 13 15]

d=np.linspace(1,15,9 , dtype=int)
print(d)

[ 1  2  4  6  8  9 11 13 15]


In [308]:
#Create a function sorting_hat() that takes in a list of celebrity names and a list of Hogwarts houses from Harry Potter and outputs a combinantion of random name
#  and random house in the following form: 'Chris Hemsworth is going to Hufflepuff!' You may use the provided list of celebrities or make your own.

#names = ['Bobby Fisher', 'Beyonce', 'Arnold Schwarzenegger', 'Akira Kurosawa', 'Britney Spears', 'Alexander the Great', 'Chris Hemsworth', 'David Lynch', 'Madonna', 'Anthony Mackie']

#houses = ['Griffindor', 'Hufflepuff', 'Slytherin', 'Ravenclaw']

#Random names and houses > use .random.choice( n , h)
# n= name , h = house


n = ['Morty'  , 'Rick' , 'Lana' , "Jhon wick" , 'Lorli Gilmore' , 'Blair Waldorf ' , ' Stephen Arroyo']
h = ['Griffindor', 'Hufflepuff', 'Slytherin', 'Ravenclaw' ,'Alpha Kappa Alpha ' , 'Kappa Alpha Thets' , 'Alpha sigma phi' , 'Delta psi' ]


def sorting_hat(n, h):
    anames = np.array(n)
    ahouses = np.array(h)
    
    x = np.random.choice(anames)
    y = np.random.choice(ahouses)
    
    return str(x) + " is going to " + str(y) + "!"
   

sorting_hat(n, h)

'Lorli Gilmore is going to Griffindor!'